theme: jekyll-theme-architect

title: [interceptors-spec]
description: [Interceptors specification work]

# sidebar links url
links:
  source: https://github.com/javaee/interceptors-spec
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

